FROM node:20

WORKDIR /usr/src/app/frontend
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Expone el puerto por defecto de Vite
EXPOSE 5173

# El comando para iniciar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]