version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nutricion-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nutricion-backend
    restart: always
    ports:
      - "${PORT}:4000"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: nutricion-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:4000
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: