FROM node:20 AS builder
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --ignore-scripts
COPY . .
RUN npm run build

FROM node:20
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --ignore-scripts
COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 4000
# Ejecutar el código JS compilado
CMD ["npm", "start"]